services:
  - docker:dind


stages:
  - dependencies

  - lint
    - lint_ui
    - lint_webapi

  - test
    - unit_test_ui
    - unit_test_webapi

  - build
  - deploy


install_dependencies:
  image: node:20-alpine
  stage: dependencies
  script:
    - yarn install

  only:
    - main
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules


unit_test_ui:
  image: node:20-alpine
  stage: test
  script:
    - yarn ui:test
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: pull


unit_test_webapi:
  image: node:20-alpine
  stage: test
  script:
    - yarn webapi:test
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: pull

lint_ui:
  image: node:20-alpine
  stage: test
  script:
    - yarn ui:lint
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: pull


lint_webapi:
  image: node:20-alpine
  stage: test
  script:
    - yarn webapi:lint
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: pull


build:
  image: node:20-alpine
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: pull

