# Dockerfile.test
FROM node:22-alpine

WORKDIR /app

# Copy necessary files and install dependencies
# COPY package.json yarn.lock eslint.config.js angular.json cypress.config.ts jest.config.ts tsconfig.app.json tsconfig.json tsconfig.spec.json ./src ./

COPY package.json yarn.lock ./


RUN yarn install

# Copy the rest of the application files
COPY . .

# Run the tests
CMD ["yarn", "test"]
