version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - .:/app
    environment:
      - NODE_ENV=test

  lint:
    build:
      context: .
      dockerfile: Dockerfile-lint
    volumes:
      - .:/app
    environment:
      - NODE_ENV=test
