version: "3.7"
services:
  das_ui:
    container_name: das_ui
    image: public.ecr.aws/x0r2c3f9/das:das_ui-latest

    environment:
      - NODE_ENV="production"

    depends_on:
      - das_webapi # nginx upstream needs das_webapi to be up

    networks:
      - das_network

    ports:
      - "80:80"

  #    volumes:
  #      - ./apps/ui/nginx/nginx.conf:/etc/nginx/nginx.conf
  #


  das_webapi:
    container_name: das_webapi
    image: public.ecr.aws/x0r2c3f9/das:das_webapi-latest
    restart: always


    environment:
      - NODE_ENV="production"
      - APP_PORT=3000
      - APP_NAME="Dashboard Starter Data"
      - API_PREFIX=das-api
      - APP_FALLBACK_LANGUAGE=en
      - APP_HEADER_LANGUAGE=x-custom-lang
      - MONGO_URI=mongodb://das_mongodb:27017
      - MONGO_DB_NAME=das_data

    depends_on:
      - das_mongodb


    networks:
      - das_network

    ports:
      - "3000:3000"



  das_mongodb:
    image: public.ecr.aws/x0r2c3f9/das:das_mongodb-latest
    container_name: das_mongodb


    command: ["/init-mongo.sh"]

    restart: always

    networks:
      - das_network

    ports:
      - "27017:27017"


networks:
  das_network:
    name: das_network
    driver: bridge
