import { DasWidgetOption } from '../../../common/components/dashboard-core/services/das-widget-option';

export const DEFAULT_WIDGET_OPTIONS: DasWidgetOption[] = [
  {
    hasContent: true,
    originalRows: 9,
    isSettingModalVisible: false,
    title: 'Sp500 Annual Returns',
    cols: 4,
    rows: 8,
    x: 5,
    y: 0,
    id: 0,
    widgetClassName: 'DvSp500WidgetComponent',
    settingData: { isTitleVisible: false },
    isMinimized: false,
    isShowRefreshButton: true,
    isShowFlipButton: true,
    isFrontShown: true
  },
  {
    hasContent: true,
    originalRows: 5,
    isSettingModalVisible: false,
    title: 'Widget A',
    cols: 2,
    rows: 5,
    x: 0,
    y: 8,
    id: 1,
    widgetClassName: 'DvDemoAWidgetComponent',
    settingData: {},
    isMinimized: false,
    isShowRefreshButton: true,
    isShowFlipButton: true,
    isFrontShown: true
  },
  {
    hasContent: true,
    originalRows: 7,
    isSettingModalVisible: false,
    title: 'Widget C',
    cols: 3,
    rows: 7,
    x: 9,
    y: 6,
    id: 2,
    widgetClassName: 'DvDemoCWidgetComponent',
    settingData: {},
    isMinimized: false,
    isShowRefreshButton: true,
    isShowFlipButton: true,
    isFrontShown: true
  },
  {
    hasContent: true,
    originalRows: 5,
    isSettingModalVisible: false,
    title: 'Widget A',
    cols: 3,
    rows: 5,
    x: 2,
    y: 8,
    id: 3,
    widgetClassName: 'DvDemoAWidgetComponent',
    settingData: {},
    isMinimized: false,
    isShowRefreshButton: true,
    isShowFlipButton: true,
    isFrontShown: true
  },
  {
    hasContent: true,
    originalRows: 7,
    isSettingModalVisible: false,
    title: 'Dashboard Starter UI LOC',
    cols: 3,
    rows: 6,
    x: 9,
    y: 0,
    id: 4,
    widgetClassName: 'DvLocWidgetComponent',
    settingData: {},
    isMinimized: false,
    isShowRefreshButton: true,
    isShowFlipButton: false,
    isFrontShown: true
  },
  {
    hasContent: true,
    originalRows: 5,
    isSettingModalVisible: false,
    title: 'Widget A',
    cols: 4,
    rows: 5,
    x: 5,
    y: 8,
    id: 5,
    widgetClassName: 'DvDemoAWidgetComponent',
    settingData: {},
    isMinimized: false,
    isShowRefreshButton: true,
    isShowFlipButton: true,
    isFrontShown: true
  },
  {
    hasContent: true,
    originalRows: 9,
    isSettingModalVisible: false,
    title: 'Housing Market',
    cols: 5,
    rows: 8,
    x: 0,
    y: 0,
    id: 6,
    widgetClassName: 'DvDemoAWidgetComponent',
    settingData: {},
    isMinimized: false,
    isShowRefreshButton: true,
    isShowFlipButton: true,
    isFrontShown: true
  }
];
